name: Docker Image Build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/apps/**"
      - "**/.dockerignore"
      - "**/.gitignore"
      - "**/config.yml.example"
      - "**/docker-compose.yml.example"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.FAQ_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FAQ_DOCKERHUB_TOKEN }}

      - name: Setup builder
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - run: docker buildx create --name builder --driver docker-container --platform linux/amd64,linux/arm64 --use
      - run: docker buildx inspect --bootstrap

      - name: Build image and push
        run: docker buildx build -t moefaq/mylittleconverter:latest -t moefaq/mylittleconverter:py3.12 --platform linux/amd64,linux/arm64 --progress plain --push -f Dockerfile .